Add region fixer and refactor the write_log
StroopwafelCFW/wafel_setup_mlc pull request #6
Opened 2024-03-09 02:58 UTC by Lazr1026

* The code will check for an installed Wii U Menu and set the region values in the `sys_prod.xml` to the right one for that region.
* The write_log function is now `log_printf` and works better imo
(the top one was cleaned up by Gary, the bottom one was done entirely by Gary)

2024-03-09 22:51 UTC, jan-hofmeier requested changes
Move Sysprod stuff to it's own file

2024-03-09 22:51 UTC, jan-hofmeier commented on source/setup.c
> +// Both MCP_GetSysProdSettings and MCP_SetSysProdSettings are from recovery_menu and were modified for use with stroopwafel.
I would rather have these functions in their own file

2024-03-09 22:51 UTC, jan-hofmeier commented on source/setup.h
> +#include <wafel/ios/svc.h>
better have that in it's own header compaining the c file for the Sysprod functions

2024-03-10 01:32 UTC, jan-hofmeier requested changes

2024-03-10 01:32 UTC, jan-hofmeier commented on source/setup.c
> +        return -1;
don't crash the whole setup, just give a warning by changing the LED, write it to log and don't do the sysprod stuff

2024-03-10 01:37 UTC, jan-hofmeier requested changes

2024-03-10 01:37 UTC, jan-hofmeier commented on source/setup.h
> +}
why have this in setup.h?

2024-03-10 01:45 UTC, Lazr1026 commented on source/setup.h
> +}
should it be in the setup.c?

2024-03-10 01:48 UTC, Lazr1026 commented on source/setup.h
> +}
or maybe the sysprod.c makes more sense

2024-03-10 11:04 UTC, jan-hofmeier approved these changes

2024-03-10 22:07 UTC, merged